### ISSUE TITLE
add dailyaveragetable service

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/monitoring-custom-service#2]
The **monitoring-custom-service** is set up to allow for the creation of different types of products. This task is multi-part but relatively straightforward and you are encouraged to break it up into separate tasks if you want. 

Note that service and parameter names are all lowercase so that end users don't need to keep track of capitalization.

The goal is to add a new service that produces multi-monitor tables of daily averages. The [current API](https://tools-c4.airfire.org/monitor-custom/v4/) will be extended to include a new service:

```
    "dailyaveragetable": {
      "method": "GET",
      "params": {
        "monitors": "monitor ID. [repeatable parameter, will be deprecated in favor of monitorids]",
        "monitorids": "Comma-separated list of monitorIDs. [ignored if monitors is defined]",
        "startdate": "Start date (inclusive). [default = 'enddate' - 'days'; otherwise string in YYYYmmdd format (e.g. 20190820)]",
        "enddate": "End date (exclusive). [default = 'startdate' + 'days' or tomorrow if 'startdate' is not explicitly specified; otherwise string in YYYYmmdd format (e.g. 20190820)]",
        "days": "Days of data to include if either 'startdate' or 'enddate' is not explicitly specified. [default = 7; otherwise a positive integer]",
        "timezone": "Olson timezone name used to interpret 'startdate' and 'enddate'. [default = 'UTC']",
        "outputfiletype": "file type of the output graphic [default = png; png|pdf]",
        "responsetype": "response type [default = raw; raw|json]",
        "language": "[not implemented] language code [default = en; en|es]"
      }
```

Here is the recommended approach:

**Duplicate dailyhourlybarplot functionality at a different URL route**
- [x] copy the contents of `monitor-custom/R/dailyhourlybarplot/` to `monitor-custom/R/dailyaveragetable/`
- [x] rename only where needed to `dailyaveragetable`
- [x] modify `monitor-custom/R/sharedUtils/createAPIList.R` to describe the `dailyaveragetable` route
- [x] test that you can retrieve a `dailyhourlybarplot` product at the `dailyaveragetable` route

**Add table functionality**
- [x] review[ table creation packages](https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r/) and choose your favorite package for creating png/pdf tables. _(Note that **flextable** works with the **offficer** package below.)_
- [x] add your table package to `monitor-custom/monitor-custom-app.R`
- [x] modify `dailyaveragetable/createProduct.R` to output a table graphic
- [x] test that you can retrieve a table from the `dailyaveragetable` route

**Refine table functionality**
- [x] modify the APIList and other functions to remove unused bits left over from `dailyhourlybarplot`
- [x] _?provide an `useaqi=TRUE` option (defaulting to `FALSE`) to convert averages from pm2.5 to AQI (basically just use monitor_nowcast() instead of PM2.5 before averaging)_

**Output Excel**
- [x] use the officer package to create Excel output
- [x] modify `createInfoList.R` and `monitor-custom/monitor-custom-app.R` to handle the new mime type
- [x] test, test, test

**Comment by tabrasel** [comment]
- [ ] include any new package dependencies for this service in the app's Dockerfile
